// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8XhtGGu-UFDr_CW8OXmv0FqYuxwLVug',
    appId: '1:277880989849:web:9d49b3947f1c3edf4b3008',
    messagingSenderId: '277880989849',
    projectId: 'herhack-28948',
    authDomain: 'herhack-28948.firebaseapp.com',
    storageBucket: 'herhack-28948.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAvqfSOTomGnebbY-ZmVb5KtLRarhapM',
    appId: '1:277880989849:android:672edc04a158550d4b3008',
    messagingSenderId: '277880989849',
    projectId: 'herhack-28948',
    storageBucket: 'herhack-28948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqDKDac63bdPXjl2jPjqI4AGkymQiIPy8',
    appId: '1:277880989849:ios:4cfc1cac8e187b7f4b3008',
    messagingSenderId: '277880989849',
    projectId: 'herhack-28948',
    storageBucket: 'herhack-28948.firebasestorage.app',
    iosBundleId: 'com.example.tinkHerHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqDKDac63bdPXjl2jPjqI4AGkymQiIPy8',
    appId: '1:277880989849:ios:4cfc1cac8e187b7f4b3008',
    messagingSenderId: '277880989849',
    projectId: 'herhack-28948',
    storageBucket: 'herhack-28948.firebasestorage.app',
    iosBundleId: 'com.example.tinkHerHack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_8XhtGGu-UFDr_CW8OXmv0FqYuxwLVug',
    appId: '1:277880989849:web:7987f00573de1c184b3008',
    messagingSenderId: '277880989849',
    projectId: 'herhack-28948',
    authDomain: 'herhack-28948.firebaseapp.com',
    storageBucket: 'herhack-28948.firebasestorage.app',
  );
}
